experiment:
  name: dermamnist_C_kfold_fold4
  seed: 42
  output_dir: /scratch/lustre/home/saan1491/hqcnn_project/outputs

dataset:
  root: /scratch/lustre/home/saan1491/hqcnn_project/data
  use_kfold: true
  fold_index: 4
  n_splits: 5

training:
  batch_size: 128
  num_workers: 4
  device: cuda
  epochs: 20
  lr: 0.0005
  weight_decay: 0.01

model:
  name: resnet18_quantum_8_frozen
  pretrained_backbone: /scratch/lustre/home/saan1491/hqcnn_project/outputs/dermamnist_resnet18_small_v2_seed42/best_model.pt
