experiment:
  name: c7_interface_C_32_8_seed42
  seed: 42
  output_dir: /scratch/lustre/home/saan1491/hqcnn_project/outputs/chapter7/interface

dataset:
  root: /scratch/lustre/home/saan1491/hqcnn_project/data

training:
  batch_size: 128
  num_workers: 4
  device: cuda
  epochs: 20
  lr: 0.0005
  weight_decay: 0.01

model:
  name: resnet18_quantum_32_8_frozen
  pretrained_backbone: /scratch/lustre/home/saan1491/hqcnn_project/outputs/dermamnist_resnet18_small_v2_seed42/best_model.pt
