experiment:
  name: dermamnist_resnet18_bottleneck_8_frozen_tune1
  seed: 42
  output_dir: outputs

dataset:
  name: dermamnist
  root: /scratch/lustre/home/saan1491/hqcnn_project/data

model:
  name: resnet18_bottleneck_8_frozen
  num_classes: 7
  pretrained_backbone: outputs/dermamnist_resnet18_small_v2_seed42/best_model.pt

training:
  epochs: 20
  batch_size: 128
  num_workers: 4
  device: cuda
  lr: 0.0005
  weight_decay: 0.01
